# Where things are
source:       .
destination:  public
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# author
author:
  name: 'Andreas Dieckmann'
  url: https://github.com/diecknet

# data
hello:
  en: Hello!
  de: Hallo!

plugins: [jekyll-polyglot, jekyll-paginate]
# Permalinks
permalink: pretty

include: ['_pages']
exclude: ['LICENSE.md', 'README.md', 'publi.sh', 'Gemfile.lock']
# Setup
title:            Polyglot
tagline:          'Straightforward I18n for Jekyll Blogs'
description:
  de: Ein sprachunterstützung plugin für <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, die Unterstützung der Internationalisierung schnell und intuitiv macht, für Blogs groß und klein. Hergestellt von <a href="https://github.com/untra" target="_blank">@untra</a>.
  en: A i18n support plugin for <a href="http://jekyllrb.com" target="_blank">Jekyll</a> that makes multi-language support fast and intuitive, for blogs big and small. Made by <a href="https://github.com/untra" target="_blank">@untra</a>.

# url: https://polyglot.untra.io

paginate: 5
# Custom vars
version: 1.3.1

github:
  repo: https://github.com/diecknet/diecknet-blog

#Polyglot
languages: ["en", "de"]
default_lang: "de"
exclude_from_localization: ["javascript", "images", "css", "public"]
data_dir: ./_data
