# Where things are
source:       .
destination:  public
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Conversion
markdown:    kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
      default_lang: powershell
      css_class   : 'highlight'
      span:
        line_numbers: false
      block:
        line_numbers: true
        start_line: 1
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# author
author:
  name: 'Andreas Dieckmann'
  url: https://github.com/diecknet

# data
hello:
  en: Hello!
  de: Hallo!
# this is custom, not from polyglot
languages_fullname:
  en: English
  de: Deutsch

github:
  repo: https://github.com/diecknet/diecknet-blog

# Permalinks
permalink: pretty

include: ['_pages']
exclude: ['LICENSE.md', 'README.md', 'publi.sh', 'Gemfile.lock']
# Setup
title:            Diecknet
tagline:          'Welcome to the blog of <span class="w3-tag">Andreas Dieckmann</span>'
description:
  de: Diecknet ist der IT-Blog von Andreas Dieckmann.
  en: Diecknet is the IT-Blog of Andreas Dieckmann.

url: https://diecknet.de

## PLUGIN CONF
plugins: [jekyll-polyglot, jekyll-paginate, jekyll-archives, jekyll-minifier]

paginate: 5
# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50
# Custom vars
version: 0.0.1

#Polyglot
languages: ["de", "en"]
default_lang: "de"
exclude_from_localization: ["img", "css", "fonts"]
data_dir: ./_data

# archives / tags
jekyll-archives:
  enabled: [tags]
  layout: tags-archive
  layouts:
    tag: tags-archive
  permalinks:
    tag: '/tags/:name/'
tag_dir: tags

# jekyll-minifier
jekyll-minifier:
  remove_spaces_inside_tags: true