# Where things are
source:       .
destination:  public
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# author
author:
  name: 'Andreas Dieckmann'
  url: https://github.com/diecknet

# data
hello:
  en: Hello!
  de: Hallo!
# this is custom, not from polyglot
languages_fullname:
  en: English
  de: Deutsch
language_translation_missing:
  en: "This content is not available in English yet. Here is the original content:"
  de: "Dieser Inhalt ist noch nicht auf Deutsch verfügbar. Hier ist der originale Inhalt:"

github:
  repo: https://github.com/diecknet/diecknet-blog


plugins: [jekyll-polyglot, jekyll-paginate, jekyll-archives]
# Permalinks
permalink: pretty

include: ['_pages']
exclude: ['LICENSE.md', 'README.md', 'publi.sh', 'Gemfile.lock']
# Setup
title:            Diecknet
tagline:          'Welcome to the blog of <span class="w3-tag">Andreas Dieckmann</span>'
description:
  de: Diecknet ist der IT-Blog von Andreas Dieckmann.
  en: Diecknet is the IT-Blog by Andreas Dieckmann.

# url: https://polyglot.untra.io

paginate: 5
# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50
# Custom vars
version: 1.3.1

#Polyglot
languages: ["de", "en"]
default_lang: "de"
exclude_from_localization: ["img", "css", "fonts"]
data_dir: ./_data

# archives
jekyll-archives:
  enabled: [tags]
  layout: tags-archive
  layouts:
    tag: tags-archive
  permalinks:
    tag: '/tags/:name/'
