name: Add links to archive.org
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  add-links:
    runs-on: ubuntu-latest
    container:
      image: secsi/waybackpy:3.0.6
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Run waybackpy to archive a page (test)
        run: waybackpy --url "https://en.wikipedia.org/wiki/Social_media" --user_agent "diecknet-blog-archiver" --save